# .github/workflows/ci-links.yml
name: ci-links
on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.mdx"

jobs:
  internal-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - run: pip install requests
      
      - run: python scripts/check_links.py