# .github/workflows/ci-markdown.yml
name: ci-markdown
on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - "**/*.mdx"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - run: npm install -g markdownlint-cli2
      
      - run: markdownlint-cli2 "**/*.md" --config ".markdownlint-cli2.yaml"