config:
  default: true

  MD013:
    line_length: 120

  MD033:
    allowed_elements:
      - br
      - details
      - summary

  MD041: false

globs:
  - "**/*.md"

ignores:
  - "**/node_modules/**"
  - "**/.git/**"
  - "**/.github/**/CODEOWNERS"
