import os
from pathlib import Path

AREAS = [
    ("academy", "Courses, lessons, labs, and progression"),
    ("fieldmanual", "Operator-grade truth by domain: failure modes, diagnostics, rollback"),
    ("blueprints", "Repeatable implementation patterns you can standardize at scale"),
    ("toolkit", "Runnable utilities (automation, audits, validators)"),
    ("sdk", "Reusable API helpers and client libraries"),
    ("scenarios", "End-to-end simulations that prove concepts in context"),
    ("grader", "Validation harness and scoring rules"),
    ("operator-os", "Cadence: runbooks, checklists, governance routines"),
    ("docs", "Standards, templates, schemas, snippets"),
    ("platform", "Delivery surface (site/docs/app) when wired in"),
    ("sandbox", "Safe scratch space"),
]

EXCLUDE_DIRS = {".git", "node_modules", ".github", "__pycache__"}

def list_children(area_path: Path) -> list[Path]:
    if not area_path.exists():
        return []
    children = []
    for p in area_path.iterdir():
        if p.is_dir() and p.name not in EXCLUDE_DIRS and not p.name.startswith("."):
            children.append(p)
    return sorted(children, key=lambda x: x.name.lower())

def md_link(path: str, label: str | None = None) -> str:
    label = label or path
    return f"[{label}]({path})"

def build_catalog(root: Path) -> str:
    lines: list[str] = []
    lines.append("# Catalog")
    lines.append("")
    lines.append("This file is auto-generated by scripts/build_catalog.py.")
    lines.append("")
    lines.append("## Areas")
    lines.append("")

    for area, desc in AREAS:
        lines.append(f"### {area}")
        lines.append(desc)
        lines.append("")
        area_path = root / area
        if not area_path.exists():
            lines.append("_Folder missing._")
            lines.append("")
            continue

        children = list_children(area_path)
        if not children:
            lines.append("_No content yet._")
            lines.append("")
            continue

        for child in children:
            rel = child.relative_to(root).as_posix()
            # Prefer README link if present
            readme = child / "README.md"
            if readme.exists():
                lines.append(f"- {md_link(rel + '/README.md', child.name)}")
            else:
                lines.append(f"- {md_link(rel + '/', child.name)}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"

def main() -> int:
    root = Path(os.getcwd()).resolve()
    out = root / "docs" / "CATALOG.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_catalog(root), encoding="utf-8")
    print(f"Wrote {out.as_posix()}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
